title: Game Dev Book
description: A Jeykll starter template test! 
theme: just-the-docs

url: https://omundy.github.io/game-dev-book

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
